# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoArticulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('apellidos', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(default=None, max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Estudiante')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Articulo')),
                ('argumento', models.CharField(max_length=1000)),
                ('titulo', models.CharField(max_length=100)),
                ('edicion', models.CharField(max_length=20)),
                ('anio_publicacion', models.CharField(max_length=4)),
                ('fecha_ingreso', models.DateTimeField()),
                ('autores', models.ManyToManyField(to='polls.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Articulo')),
                ('resumen', models.CharField(max_length=1000)),
                ('anio_publicacion', models.CharField(max_length=4)),
                ('fecha_ingreso', models.DateTimeField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asesor')),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='articulos',
            field=models.ManyToManyField(to='polls.Articulo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EstadoPrestamo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EstadoArticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TipoArticulo'),
        ),
    ]
